export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
  

      <main>{children}</main>
    
  )
}

export default Layout